local colors = require("base16").get_theme_tb("base_30")
local theme = require("base16").get_theme_tb("base_16")

return {
	CmpItemAbbr = { fg = colors.white },
	CmpItemAbbrMatch = { fg = colors.blue, bold = true },
	CmpBorder = { fg = colors.grey },
	CmpDocBorder = { fg = colors.grey },
	CmpItemKindConstant = { fg = theme.base09 },
	CmpItemKindFunction = { fg = theme.base0D },
	CmpItemKindIdentifier = { fg = theme.base08 },
	CmpItemKindField = { fg = theme.base08 },
	CmpItemKindVariable = { fg = theme.base0E },
	CmpItemKindSnippet = { fg = colors.red },
	CmpItemKindText = { fg = theme.base0B },
	CmpItemKindStructure = { fg = theme.base0E },
	CmpItemKindType = { fg = theme.base0A },
	CmpItemKindKeyword = { fg = theme.base07 },
	CmpItemKindMethod = { fg = theme.base0D },
	CmpItemKindConstructor = { fg = colors.blue },
	CmpItemKindFolder = { fg = theme.base07 },
	CmpItemKindModule = { fg = theme.base0A },
	CmpItemKindProperty = { fg = theme.base08 },
	CmpItemKindUnit = { fg = theme.base0E },
	CmpItemKindFile = { fg = theme.base07 },
	CmpItemKindColor = { fg = colors.red },
	CmpItemKindReference = { fg = theme.base05 },
	CmpItemKindStruct = { fg = theme.base0E },
	CmpItemKindOperator = { fg = theme.base05 },
	CmpItemKindTypeParameter = { fg = theme.base08 },
}
