local colors = require("base16").get_theme_tb("base_30")

return {
	LspReferenceRead = { bg = colors.grey, bold = true },
	LspReferenceText = { bg = colors.grey, bold = true },
	LspCodeLens = { fg = colors.grey },
	LspInfoBorder = { fg = colors.blue, bg = colors.black },
	LspReferenceWrite = { bg = colors.grey, bold = true },
	DiagnosticHint = { fg = colors.purple },
	DiagnosticError = { fg = colors.red },
	DiagnosticWarn = { fg = colors.yellow },
	DiagnosticInformation = { fg = colors.green },
	LspSignatureActiveParameter = { fg = colors.black, bg = colors.green },
	RenameTitle = { fg = colors.black, bg = colors.blue },
	RenameBorder = { fg = colors.grey, bg = colors.black },
	["@lsp.type.interface"] = { fg = colors.blue },
	["@lsp.typemod.type.defaultLibrary"] = { fg = colors.blue },
	["@lsp.type.comment"] = { link = "@comment" },
	["@lsp.type.enum"] = { link = "@type" },
	["@lsp.type.enumMember"] = { link = "@constant" },
	["@lsp.type.keyword"] = { link = "@keyword" },
	["@lsp.type.namespace"] = { link = "@namespace" },
	["@lsp.type.parameter"] = { link = "@parameter" },
	["@lsp.type.property"] = { link = "@property" },
	["@lsp.type.variable"] = {},
	["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
	["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
	["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
	["@lsp.typemod.operator.injected"] = { link = "@operator" },
	["@lsp.typemod.string.injected"] = { link = "@string" },
	["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
	["@lsp.typemod.variable.injected"] = { link = "@variable" },
}
