local colors = require("base16").get_theme_tb("base_30")
local theme = require("base16").get_theme_tb("base_16")

return {
  NavicIconsIdentifier = { fg = theme.base08 },
  NavicIconsSnippet = { fg = colors.red },
  NavicIconsText = { fg = theme.base0B },
  NavicIconsStructure = { fg = theme.base0E },
  NavicIconsType = { fg = theme.base0A },
  NavicIconsFolder = { fg = theme.base07 },
  NavicIconsUnit = { fg = theme.base0E },
  NavicIconsColor = { fg = colors.white },
  NavicIconsReference = { fg = theme.base05 },
  NavicIconsValue = { fg = colors.cyan },
  NavicIconsFile = { fg = theme.base07 },
  NavicIconsModule = { fg = theme.base0A },
  NavicIconsNamespace = { fg = theme.base0A },
  NavicIconsPackage = { fg = theme.base0A },
  NavicIconsClass = { fg = colors.orange, bg = "NONE" },
  NavicIconsArray = { fg = colors.orange, bg = "NONE" },
  NavicIconsObject = { fg = colors.orange, bg = "NONE" },
  NavicIconsMethod = { fg = theme.base0D },
  NavicIconsProperty = { fg = theme.base08 },
  NavicIconsField = { fg = theme.base08 },
  NavicIconsConstructor = { fg = colors.blue, bg = "NONE" },
  NavicIconsEnum = { fg = colors.orange, bg = "NONE" },
  NavicIconsInterface = { fg = colors.orange, bg = "NONE" },
  NavicIconsFunction = { fg = colors.purple, bg = "NONE" },
  NavicIconsVariable = { fg = colors.blue, bg = "NONE" },
  NavicIconsConstant = { fg = colors.blue, bg = "NONE" },
  NavicIconsString = { fg = colors.orange, bg = "NONE" },
  NavicIconsNumber = { fg = colors.green, bg = "NONE" },
  NavicIconsBoolean = { fg = colors.blue, bg = "NONE" },
  NavicIconsKey = { fg = colors.white, bg = "NONE" },
  NavicIconsKeyword = { fg = colors.white, bg = "NONE" },
  NavicIconsNull = { fg = colors.blue, bg = "NONE" },
  NavicIconsEnumMember = { fg = colors.blue, bg = "NONE" },
  NavicIconsStruct = { fg = colors.orange, bg = "NONE" },
  NavicIconsEvent = { fg = colors.yellow, bg = "NONE" },
  NavicIconsOperator = { fg = colors.white, bg = "NONE" },
  NavicIconsTypeParameter = { fg = colors.white, bg = "NONE" },
  NavicText = { fg = colors.grey, bg = "NONE" },
  NavicSeparator = { fg = colors.grey, bg = "NONE" },
}
